### ISSUE TITLE
CSS in JS: Estilizando aplicações modulares.

### ISSUE THREAD

**Issue by andre-araujo** [reactrio/call4papers#1]
Palestrante: André Araújo
Empresa: Concrete Solutions
Descrição da palestra:
A web vem crescendo em grande escala, aumentando também a complexidade das aplicações. Nesse cenário, arquiteturas modulares se tornaram uma forma viável para manter aplicações complexas, e com isso, são necessárias estratégias diferentes para estilizar essas aplicações, sendo uma delas, o uso de estilos por meio do JavaScript, o que olharemos um pouquinho mais de perto nessa talk.

Onde me encontrar?

GitHub: [andre-araujo](https://github.com/andre-araujo)
LinkedIn: [andreluissiqueiraaraujo](https://www.linkedin.com/in/andreluissiqueiraaraujo/)

**Comment by carloshpdoc** [comment]
Talk dada no meetup : https://www.meetup.com/pt-BR/React-Rio-de-Janeiro/events/251440773/
